-- Corrige excerpts quebrados (valor literal 'IA' em vez de resumo real)
-- e remove caractere de tabulação que vazou para 3 slugs na migração.

UPDATE public.blog_posts SET excerpt = 'IA automatiza tarefas repetitivas em bancos comunitários — prevenção de fraudes, análise de dados — liberando equipes para o relacionamento com clientes.' WHERE slug = 'como-a-ia-esta-revolucionando-o-atendimento-personalizado-nos-bancos-comunitarios-ate-2026--1770560893415';
UPDATE public.blog_posts SET excerpt = 'Levantamento mapeia 65 carreiras que resistem à automação por dependerem de criatividade, empatia e julgamento humano — da saúde ao design.' WHERE slug = 'quais-empregos-a-ia-nao-vai-substituir-1770422161961';
UPDATE public.blog_posts SET excerpt = 'Cortes de vagas nos EUA sobem 118% em janeiro de 2026, maior alta desde 2009. A IA é um fator crescente, mas não o principal responsável pelas demissões.' WHERE slug = 'corte-de-empregos-nos-eua-sobe-118-em-janeiro-de-2026-qual-o-papel-da-ia-1770422127136';
UPDATE public.blog_posts SET excerpt = 'A IA ameaça o modelo de receita recorrente do software tradicional, capaz de substituir funções de sistemas como ERP e CRM com menos infraestrutura.' WHERE slug = 'software-e-ia-o-fim-dos-modelos-tradicionais-ou-nova-oportunidade--1770293401367';
UPDATE public.blog_posts SET excerpt = 'O Claude Cowork, da Anthropic, automatiza funções legais, de vendas e análise de dados — e já derrubou quase 6% o índice de tecnologia da Índia.', slug = '-impacto-revolucionario-da-ia-nos-negocios-o-caso-anthropic-e-o-futuro-do-setor-de-ti-1770293355365' WHERE slug = '	-impacto-revolucionario-da-ia-nos-negocios-o-caso-anthropic-e-o-futuro-do-setor-de-ti-1770293355365';
UPDATE public.blog_posts SET excerpt = 'Estudo aponta que 59% da força de trabalho de Quebec tem alta exposição à IA, com impacto desigual entre gênero, escolaridade e tipo de função.' WHERE slug = 'impacto-da-ia-na-forca-de-trabalho-de-quebec-o-que-voce-precisa-saber-1770293290481';
UPDATE public.blog_posts SET excerpt = 'Sam Altman projeta empresas 100% operadas por IA. Para ele, o maior obstáculo não é tecnológico, mas a falta de preparo estrutural das organizações.' WHERE slug = 'sam-altman-sobre-o-futuro-das-empresas-100-ia-estamos-prontos--1770208903169';
UPDATE public.blog_posts SET excerpt = 'Amazon, Oracle e Pinterest cortaram milhares de vagas. Especialistas apontam que ajustes pós-pandemia pesam tanto quanto a adoção de IA nas demissões.', slug = '-desmistificando-as-demissoes-em-grandes-empresas-de-tecnologia-a-inteligencia-artificial-e-a-unica-culpada-1770078466570' WHERE slug = '	-desmistificando-as-demissoes-em-grandes-empresas-de-tecnologia-a-inteligencia-artificial-e-a-unica-culpada-1770078466570';
UPDATE public.blog_posts SET excerpt = 'Em 2026, a IA deixou de ser promessa para resolver desafios concretos em governos e saúde, com foco em implantação responsável e valor prático mensurável.', slug = '-ia-resolvendo-problemas-reais-em-escala-e-gerando-roi-estrategico-1769740606799' WHERE slug = '	-ia-resolvendo-problemas-reais-em-escala-e-gerando-roi-estrategico-1769740606799';
UPDATE public.blog_posts SET excerpt = 'A Ypê aprofunda sua parceria com IA Agente aplicada ao ERP e reduz processos de oito para dois passos manuais, com ganhos expressivos de eficiência.' WHERE slug = 'ype-revoluciona-com-ia-agente-maximizando-o-erp-e-acelerando-a-transformacao-digital-1769566158729';
UPDATE public.blog_posts SET excerpt = '93% dos profissionais na Malásia já usam IA generativa no dia a dia. A produtividade sobe, mas 68% relatam aumento na carga de trabalho.' WHERE slug = 'ia-e-forca-de-trabalho-malasia-lidera-em-produtividade-mas-enfrenta-desafios-cruciais--1769513385828';
UPDATE public.blog_posts SET excerpt = 'Relatório do Fórum Econômico Mundial prevê remodelação radical do mercado de trabalho até 2030, com ganhos de margem e deslocamento de vagas pela IA.' WHERE slug = 'ia-transformara-empregos-ate-2030-o-que-o-wef-preve-para-o-mercado--1769377674678';
UPDATE public.blog_posts SET excerpt = 'Os LLMs operam por trás de funções que usamos todos os dias, muito além do ChatGPT — entenda como essa tecnologia move a automação de processos.' WHERE slug = 'desvende-os-llms-a-ia-oculta-que-otimiza-seus-processos-e-impulsiona-a-transformacao-digital--1769346870976';
UPDATE public.blog_posts SET excerpt = 'Cache de contexto aplicado a RAG com Google Gemini melhora a precisão e a consistência das respostas de LLMs em processos de negócio.' WHERE slug = 'rag-com-google-gemini-ai-otimize-a-automacao-e-consistencia-com-cache-de-contexto--1769346834658';
UPDATE public.blog_posts SET excerpt = 'A IA generativa deixou de ser passiva: agentes autônomos multimodais já criam conteúdo original e interpretam intenções humanas complexas.' WHERE slug = 'desvende-a-era-da-ia-generativa-como-agentes-autonomos-redefinem-o-futuro-dos-negocios--1769346790099';
UPDATE public.blog_posts SET excerpt = 'Ganhos de otimização de prompts podem ser só ruído estatístico. Entenda a ''falésia estocástica'' e como garantir ROI real em projetos de IA.' WHERE slug = 'otimizacao-de-prompts-llm-elimine-a-variancia-e-garanta-o-roi-da-sua-ia--1769346731049';
